[package]
name = "ryaspeller"
version = "0.1.0"
authors = ["oriontvv <taranov.vv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ryaspeller"
path = "src/lib.rs"

[[bin]]
name = "ryaspeller"
path = "src/bin/main.rs"

[dependencies]
clap = "3.0.0-beta.2"
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
serde = "1.0.126"
serde_json = "1.0.64"
thiserror = "1.0"
