[package]
name = "ryaspeller"
version = "0.1.0"
authors = ["oriontvv <taranov.vv@gmail.com>"]
edition = "2018"
description = "A tool and lib for searching typos in text, files and websites"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
anyhow = "1.0.42"
