
name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release-crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish package to crates
        run: |
          cargo package
          cargo publish --token ${{ secrets.CARGO_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      
      - name: Build
        run: cargo build --all --release && strip target/release/ryaspeller && mv target/release/ryaspeller target/release/ryaspeller_amd64

      - name: Upload binary
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ryaspeller_amd64
          path: target/release/ryaspeller_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/ryaspeller_amd_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/ryaspeller_amd64
          asset_name: ryaspeller_amd64
          tag: ${{ github.ref }}
          overwrite: true

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release
      
      - name: Upload binary
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ryaspeller.exe
          path: target/release/ryaspeller.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/ryaspeller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/ryaspeller.exe
          asset_name: ryaspeller.exe
          tag: ${{ github.ref }}
          overwrite: true
  
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/ryaspeller && mv target/release/ryaspeller target/release/ryaspeller_darwin

      - name: Upload binary
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ryaspeller_darwin
          path: target/release/ryaspeller_darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/ryaspeller_darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/ryaspeller_darwin
          asset_name: ryaspeller_darwin
          tag: ${{ github.ref }}
          overwrite: true
